version: '3.9'
name: taw_app
services:
  backend:
    build: backend
    container_name: taw_backend
    ports:
      - "3100:3100"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/sendgrid.env
    environment:
      - HOST=0.0.0.0
      - PORT=3100
    command: npm run start

  frontend:
    build: frontend
    container_name: taw_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/src/app
    command: npm start
